version: '3.8'
services:
  # Node.js service
  node_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node_container
    restart: always
    volumes:
      - ./server:/server
    ports:
      - '3000:3000'
    depends_on:
      - mongo

  # MongoDB service
  mongo:
    image: mongo:latest
    container_name: mongo_app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'test-user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
